<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="7DLH4Q2" name="Default test" tests="10" failures="1" timestamp="21 Mar 2020 13:39:04 GMT" time="5.327" errors="0">
  <testcase name="archieveChannelInvalidIntValueChannelId" time="0.349" classname="testcases.ArchiveChannel"/>
  <testcase name="archieveChannelInvalidStringChannelId" time="0.38" classname="testcases.ArchiveChannel"/>
  <testcase name="archieveChannelWithBlankChannelId" time="0.342" classname="testcases.ArchiveChannel"/>
  <testcase name="archieveChannelWithNullValueChannelId" time="0.343" classname="testcases.ArchiveChannel"/>
  <testcase name="archieveChannelWithBlankToken" time="0.325" classname="testcases.ArchiveChannel"/>
  <testcase name="archieveChannelWithInvalidToken" time="0.326" classname="testcases.ArchiveChannel"/>
  <testcase name="archieveChannelWithNullValueToken" time="0.362" classname="testcases.ArchiveChannel"/>
  <testcase name="archieveChannelWithoutToken" time="0.335" classname="testcases.ArchiveChannel"/>
  <testcase name="archieveChannelSuccessfully" time="0.842" classname="testcases.ArchiveChannel"/>
  <testcase name="archieveChannelWithAlreadyarchieve" time="0.327" classname="testcases.ArchiveChannel">
    <failure type="java.lang.AssertionError" message="ok mismatch expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: ok mismatch expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at testcases.ArchiveChannel.archieveChannelWithAlreadyarchieve(ArchiveChannel.java:77)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- archieveChannelWithAlreadyarchieve -->
</testsuite> <!-- Default test -->
